export const message = {
  somethingWentWrong: "Something Went wrong",
  dataIsAlreadyAvailable: "Data is already available",
  dataNotFound: "Data not found",
  dataIsNotCreated: "Data is not Created",
  dataIsNotDeleted: "Data is  not deleted",
  dataIsNotUpdated: "Data is not updated",
  userNotFound: "User not found",
  emailAlreadyExist: "Email is already exist",
  employeeIsAlreadyExist: "Employee is already exist ",
  employeeIsNotCreated: "Employee is not created",
  employeeIsNotDeleted: "Employee is not deleted",
  employeeIsNotUpdated: "Employee is not deleted",
  clientIsAlreadyExist: "Client is already exist",
  clientIsNotCreated: "Client is not created",
  clientIsNotDeleted: "Client is not deleted",
  clientIsNotUpdated: "Client is not updated",
  agencyIsNotCreated: "agency is not created",
  stateIsAlreadyExist: "State is already exist",
  agencyIsAlreadyExist: "Agency is already exist",
  countryIsAlreadyExist: "country is alreadty exist",
  taskIsAlreadyCreated: "Task is already created",
};
